// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateClimate(ctx context.Context, arg CreateClimateParams) (ClimateNormal, error)
	CreatePlace(ctx context.Context, arg CreatePlaceParams) (Place, error)
	DeletePlace(ctx context.Context, id int32) error
	GetClimate(ctx context.Context, placeID pgtype.Int4) (ClimateNormal, error)
	GetPlace(ctx context.Context, id int32) (Place, error)
	ListPlaces(ctx context.Context, arg ListPlacesParams) ([]Place, error)
}

var _ Querier = (*Queries)(nil)
