CREATE TYPE "months" AS ENUM (
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December'
);

CREATE TABLE "places"
(
    "id"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"      varchar(100)  NOT NULL,
    "country"   varchar(100)  NOT NULL,
    "latitude"  decimal(9, 6) NOT NULL,
    "longitude" decimal(9, 6) NOT NULL,
    "altitude"  integer
);

CREATE TABLE "climate_normals"
(
    "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "place_id"     integer,
    "month"        integer NOT NULL,
    "tavg"         decimal(5, 2),
    "tmin"         decimal(5, 2),
    "tmax"         decimal(5, 2),
    "prcp"         decimal(6, 2),
    "wspd"         decimal(5, 2),
    "pres"         decimal(7, 2),
    "tsun"         integer,
    "last_updated" timestamp
);

CREATE UNIQUE INDEX ON "climate_normals" ("place_id", "month");

COMMENT
ON COLUMN "climate_normals"."month" IS 'Range: 1 to 12';

ALTER TABLE "climate_normals"
    ADD FOREIGN KEY ("place_id") REFERENCES "places" ("id");